---

- include: software.yml
  tags:
    - mrcrilly_mongodb
    - mrcrilly_mongodb_software
  when: mrcrilly_mongodb_manage_software | default(true)

- include: configuration.yml
  tags:
    - mrcrilly_mongodb
    - mrcrilly_mongodb_configuration
  when: mrcrilly_mongodb_manage_configuration | default(true)

- include: permissions.yml
  tags:
    - mrcrilly_mongodb
    - mrcrilly_mongodb_permissions
  when: mrcrilly_mongodb_manage_permissions | default(true)

# - include: service.yml
#   tags:
#     - mrcrilly_mongodb
#     - mrcrilly_mongodb_service
#   when: mrcrilly_mongodb_manage_service | default(true)
